Elcodi\UserBundle\Entity\Address:
    type: entity
    repositoryClass: Elcodi\UserBundle\Repository\AddressRepository
    table: address
    fields:
        address:
            column: address
            type: string
            length: 255
            nullable: true

        # datetime
        createdAt:
            column: created_at
            type: datetime
            nullable: true

        updatedAt:
            column: updated_at
            type: datetime

        # enable
        enabled:
            column: enabled
            type: boolean
            nullable: true

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
