Elcodi\UserBundle\Entity\AdminUser:
    type: entity
    repositoryClass: Elcodi\UserBundle\Repository\AdminUserRepository
    table: admin_user

    lifecycleCallbacks:
            preUpdate: [loadUpdateAt]
            prePersist: [loadUpdateAt]
