parameters:

    #
    # Factories
    #
    elcodi.factory.customer.class: Elcodi\Component\User\Factory\CustomerFactory
    elcodi.factory.admin_user.class: Elcodi\Component\User\Factory\AdminUserFactory

    #
    # Services
    #
    elcodi.password_manager.class: Elcodi\Component\User\Services\PasswordManager
    elcodi.customer_manager.class: Elcodi\Component\User\Services\CustomerManager
    elcodi.admin_user_manager.class: Elcodi\Component\User\Services\AdminUserManager

    #
    # Wrappers
    #
    elcodi.customer_wrapper.class: Elcodi\Component\User\Wrapper\CustomerWrapper
    elcodi.admin_user_wrapper.class: Elcodi\Component\User\Wrapper\AdminUserWrapper

    #
    # Event Listeners
    #
    elcodi.event_listener.admin_user_password.class: Elcodi\Component\User\EventListener\AdminUserPasswordEventListener
    elcodi.event_listener.customer_password.class: Elcodi\Component\User\EventListener\CustomerPasswordEventListener
    elcodi.event_listener.authentication_success.class: Elcodi\Component\User\EventListener\AuthenticationSuccessEventListener

    #
    # Providers
    #
    elcodi.abstract_user_provider.class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
