parameters:

    #
    # Entities
    #
    elcodi.core.user.entity.customer.class: Elcodi\UserBundle\Entity\Customer
    elcodi.core.user.entity.admin_user.class: Elcodi\UserBundle\Entity\AdminUser

    #
    # Factories
    #
    elcodi.core.user.factory.customer.class: Elcodi\UserBundle\Factory\CustomerFactory
    elcodi.core.user.factory.admin_user.class: Elcodi\UserBundle\Factory\AdminUserFactory

    #
    # Repositories
    #
    elcodi.core.user.repository.customer.class: Elcodi\UserBundle\Repository\CustomerRepository
    elcodi.core.user.repository.admin_user.class: Elcodi\UserBundle\Repository\AdminUserRepository

    #
    # Services
    #
    elcodi.core.user.service.password_manager.class: Elcodi\UserBundle\Services\PasswordManager
    elcodi.core.user.service.customer_manager.class: Elcodi\UserBundle\Services\CustomerManager
    elcodi.core.user.service.admin_user_manager.class: Elcodi\UserBundle\Services\AdminUserManager

    #
    # Wrappers
    #
    elcodi.core.user.wrapper.customer_wrapper.class: Elcodi\UserBundle\Wrapper\CustomerWrapper
    elcodi.core.user.wrapper.admin_user_wrapper.class: Elcodi\UserBundle\Wrapper\AdminUserWrapper

    #
    # Event Listeners
    #
    elcodi.core.user.event_listener.admin_user_password.class: Elcodi\UserBundle\EventListener\AdminUserPasswordEventListener
    elcodi.core.user.event_listener.customer_password.class: Elcodi\UserBundle\EventListener\CustomerPasswordEventListener
    elcodi.core.user.event_listener.authentication_success.class: Elcodi\UserBundle\EventListener\AuthenticationSuccessEventListener

    #
    # Generators
    #
    elcodi.core.user.generator.recover_hash.class: Elcodi\UserBundle\Generator\RecoveryHashGenerator

    #
    # Providers
    #
    elcodi.core.user.provider.abstract_user_provider.class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
