parameters:

    #
    # Entities
    #
    elcodi.core.user.entity.customer.class: Elcodi\UserBundle\Entity\Customer
    elcodi.core.user.entity.address.class: Elcodi\UserBundle\Entity\Address

    #
    # Entities
    #
    elcodi.core.user.repository.customer.class: Elcodi\UserBundle\Repository\CustomerRepository
    elcodi.core.user.repository.address.class: Elcodi\UserBundle\Repository\AddressRepository

    #
    # Services
    #
    elcodi.core.user.service.password_manager.class: Elcodi\UserBundle\Services\PasswordManager
    elcodi.core.user.service.customer_manager.class: Elcodi\UserBundle\Services\CustomerManager
    elcodi.core.user.wrapper.customer_wrapper.class: Elcodi\UserBundle\Wrapper\CustomerWrapper

    #
    # Form Types
    #
    elcodi.core.user.form_type.customer.class: Elcodi\UserBundle\Form\Type\CustomerType

    #
    # Event Listeners
    #
    elcodi.core.user.event_listener.password.class: Elcodi\UserBundle\EventListener\PasswordEventListener

    #
    # Factories
    #
    elcodi.core.user.factory.customer.class: Elcodi\UserBundle\Factory\CustomerFactory
    elcodi.core.user.factory.address.class: Elcodi\UserBundle\Factory\AddressFactory

    #
    # Generators
    #
    elcodi.core.user.generator.recover_hash.class: Elcodi\UserBundle\Generator\RecoveryHashGenerator

    #
    # Providers
    #
    elcodi.core.user.provider.customer_provider.class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
