parameters:

    #
    # Factories
    #
    elcodi.factory.customer.class: Elcodi\Component\User\Factory\CustomerFactory
    elcodi.factory.admin_user.class: Elcodi\Component\User\Factory\AdminUserFactory

    #
    # Services
    #
    elcodi.manager.password.class: Elcodi\Component\User\Services\PasswordManager
    elcodi.manager.customer.class: Elcodi\Component\User\Services\CustomerManager
    elcodi.manager.admin_user.class: Elcodi\Component\User\Services\AdminUserManager

    #
    # Wrappers
    #
    elcodi.wrapper.customer.class: Elcodi\Component\User\Wrapper\CustomerWrapper
    elcodi.wrapper.admin_user.class: Elcodi\Component\User\Wrapper\AdminUserWrapper

    #
    # Event Listeners
    #
    elcodi.event_listener.admin_user_password.class: Elcodi\Component\User\EventListener\AdminUserPasswordEventListener
    elcodi.event_listener.customer_password.class: Elcodi\Component\User\EventListener\CustomerPasswordEventListener
    elcodi.event_listener.authentication_success.class: Elcodi\Component\User\EventListener\AuthenticationSuccessEventListener

    #
    # Providers
    #
    elcodi.abstract_user_provider.class: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface

    #
    # Constraints
    #
    elcodi.validator.city_exists.class: Elcodi\Component\Geo\Validator\Constraints\CityExistsValidator
