services:

    #
    # Event Listeners
    #
    elcodi.core.user.event_listener.password:
        class: %elcodi.core.user.event_listener.password.class%
        arguments:
            encoder_blowfish: @security.encoder.blowfish
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
