services:

    #
    # Factories
    #

    #
    # Factory for entity customer
    #
    elcodi.factory.customer:
        class: %elcodi.factory.customer.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.user.entity.customer.class%"]]
            - [setGenerator, [@elcodi.generator.random_string]]

    #
    # Factory for entity admin user
    #
    elcodi.factory.admin_user:
        class: %elcodi.factory.admin_user.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.user.entity.admin_user.class%"]]
            - [setGenerator, [@elcodi.generator.random_string]]
