services:

    #
    # Form Types
    #
    elcodi.core.user.form_type.customer:
        class: %elcodi.core.user.form_type.customer.class%
        tags:
            - { name: form.type, alias: elcodi_core_form_types_customer }
