services:

    #
    # Providers
    #
    elcodi.core.user.provider.customer_provider:
        class: %elcodi.core.user.provider.abstract_user_provider.class%
        factory_service: security.encoder_factory
        factory_method: getEncoder
        arguments:
            customer_instance: @=service("elcodi.factory.customer").create()

    elcodi.core.user.provider.admin_user_provider:
        class: %elcodi.core.user.provider.abstract_user_provider.class%
        factory_service: security.encoder_factory
        factory_method: getEncoder
        arguments:
            customer_instance: @=service("elcodi.factory.admin_user").create()
