services:

    #
    # Provider user factories
    #
    elcodi.customer_provider_entity_instance:
        class: %elcodi.entity.customer.class%
        factory_service: elcodi.factory.customer
        factory_method: create

    elcodi.admin_user_provider_entity_instance:
        class: %elcodi.entity.admin_user.class%
        factory_service: elcodi.factory.admin_user
        factory_method: create

    #
    # Providers
    #
    elcodi.provider.customer_provider:
        class: %elcodi.abstract_user_provider.class%
        factory_service: security.encoder_factory
        factory_method: getEncoder
        arguments:
            customer_instance: @elcodi.customer_provider_entity_instance

    elcodi.provider.admin_user_provider:
        class: %elcodi.abstract_user_provider.class%
        factory_service: security.encoder_factory
        factory_method: getEncoder
        arguments:
            customer_instance: @elcodi.admin_user_provider_entity_instance
