services:

    #
    # Repositories
    #

    #
    # Repository for entity customer
    #
    elcodi.repository.customer:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.user.entity.customer.class% ]

    #
    # Repository for entity admin
    #
    elcodi.repository.admin_user:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.user.entity.admin_user.class% ]
