services:

    #
    # Services
    #
    elcodi.core.user.service.password_manager:
        class: %elcodi.core.user.service.password_manager.class%
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            router: @router
            event_dispatcher: @event_dispatcher
            recovery_hash_generator: @elcodi.core.user.generator.recover_hash

    elcodi.core.user.service.customer_manager:
        class: %elcodi.core.user.service.customer_manager.class%
        arguments:
            event_dispatcher: @event_dispatcher
            security_context: @?security.context

    elcodi.core.user.wrapper.customer_wrapper:
        class: %elcodi.core.user.wrapper.customer_wrapper.class%
        arguments:
            customer_repository: @elcodi.core.user.repository.customer
            session: @session
            customer_factory: @elcodi.core.user.factory.customer
            session_field_name: %elcodi.core.user.session_field_name%
            security_context: @?security.context

    elcodi.customer_wrapper:
        alias: elcodi.core.user.wrapper.customer_wrapper

    #
    # Provider
    #
    elcodi.core.user.provider.customer_provider:
        class: %elcodi.core.user.provider.customer_provider.class%
        factory_service: security.encoder_factory
        factory_method: getEncoder
        arguments:
            customer_instance: @=service("elcodi.factory.customer").create()

    elcodi.customer_provider:
        alias: elcodi.core.user.provider.customer_provider

    #
    # Generators
    #
    elcodi.core.user.generator.recover_hash:
        class: %elcodi.core.user.generator.recover_hash.class%
