services:

    #
    # Services
    #
    elcodi.password_manager:
        class: %elcodi.password_manager.class%
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            router: @router
            event_dispatcher: @event_dispatcher
            recovery_hash_generator: @elcodi.generator.sha1

    elcodi.customer_manager:
        class: %elcodi.customer_manager.class%
        arguments:
            event_dispatcher: @event_dispatcher
            security_context: @?security.context

    elcodi.admin_user_manager:
        class: %elcodi.admin_user_manager.class%
        arguments:
            event_dispatcher: @event_dispatcher
            security_context: @?security.context
