services:

    #
    # Services
    #
    elcodi.manager.password:
        class: %elcodi.manager.password.class%
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            router: @router
            event_dispatcher: @event_dispatcher
            recovery_hash_generator: @elcodi.generator.sha1

    elcodi.manager.customer:
        class: %elcodi.manager.customer.class%
        arguments:
            event_dispatcher: @event_dispatcher
            security_context: @?security.context

    elcodi.manager.admin_user:
        class: %elcodi.manager.admin_user.class%
        arguments:
            event_dispatcher: @event_dispatcher
            security_context: @?security.context
