services:

    #
    # Services
    #
    elcodi.manager.password:
        class: %elcodi.manager.password.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @router
            - @event_dispatcher
            - @elcodi.generator.sha1

    elcodi.manager.customer:
        class: %elcodi.manager.customer.class%
        arguments:
            - @event_dispatcher
            - @?security.context

    elcodi.manager.admin_user:
        class: %elcodi.manager.admin_user.class%
        arguments:
            - @event_dispatcher
            - @?security.context
