services:

    #
    # Services
    #
    elcodi.core.user.service.password_manager:
        class: %elcodi.core.user.service.password_manager.class%
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            router: @router
            event_dispatcher: @event_dispatcher
            recovery_hash_generator: @elcodi.core.user.generator.recover_hash

    elcodi.password_manager:
        alias: elcodi.core.user.service.password_manager

    elcodi.core.user.service.customer_manager:
        class: %elcodi.core.user.service.customer_manager.class%
        arguments:
            event_dispatcher: @event_dispatcher
            security_context: @?security.context

    elcodi.customer_manager:
        alias: elcodi.core.user.service.customer_manager

    elcodi.core.user.service.admin_user_manager:
        class: %elcodi.core.user.service.admin_user_manager.class%
        arguments:
            event_dispatcher: @event_dispatcher
            security_context: @?security.context

    elcodi.admin_user_manager:
        alias: elcodi.core.user.service.admin_user_manager

    #
    # Generators
    #
    elcodi.core.user.generator.recover_hash:
        class: %elcodi.core.user.generator.recover_hash.class%
