services:

    #
    # Constraints
    #
    elcodi.validator.city_exists:
        class: %elcodi.validator.city_exists.class%
        arguments:
            - @elcodi.location_provider
        tags:
            - { name: validator.constraint_validator, alias: city_exists }
