services:

    #
    # Wrappers
    #
    elcodi.customer_wrapper:
        class: %elcodi.customer_wrapper.class%
        arguments:
            customer_factory: @elcodi.factory.customer
            security_context: @?security.context

    elcodi.admin_user_wrapper:
        class: %elcodi.admin_user_wrapper.class%
        arguments:
            admin_user_factory: @elcodi.factory.admin_user
            security_context: @?security.context
